gantt
    title Registration Communications Timeline
    dateFormat YYYY-MM-DD
    axisFormat %d days

    Generate SMS Shorten Link :2024-01-01, 1d
    Generate SMS Link 15 days prio :2024-01-01, 1d
    14 days SMS Before Attendance  :2024-01-02, 1d
    1 week prior to Public course :2024-01-09, 1d
    7 Days before Public course SM :2024-01-09, 1d
    1 week prior to Private Confir :2024-01-09, 1d
    7 Days before Private Confirme :2024-01-09, 1d
    Course Day :2024-01-16, 1d
    Thank You SMS :2024-01-17, 1d
